twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        mercure_publish_url: '%env(MERCURE_PUBLISH_URL)%'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - 'form/layout.html.twig'
        - 'form/fields.html.twig'
